{
"data": [
 {
   "RecordID": 1,
   "FirstName": "Virginie",
   "LastName": "Allavena",
   "Phone": "0541 969970 and 0721 283588",
   "Email": "info@castellodigranarola.it",
   "Town": "Granarola",
   "Postcode": "",
   "Address": "Via Castello 1, \nGranarola\nGradara",
   "Notes": "\n"
 },
 {
   "RecordID": 2,
   "FirstName": "Margherita",
   "LastName": "Bugatti",
   "Phone": "338  7232032",
   "Email": "bugattimargherita@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 3,
   "FirstName": "Paolo",
   "LastName": "Manca",
   "Phone": "07890278709 UK",
   "Email": "paolomanca13@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 4,
   "FirstName": "Guglielmo e cristina",
   "LastName": "",
   "Phone": "",
   "Email": "info@asfodelihotel.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "\n"
 },
 {
   "RecordID": 5,
   "FirstName": "Tonino",
   "LastName": "Asara",
   "Phone": "329 1625081",
   "Email": "mirkantoni@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 6,
   "FirstName": "Antonio",
   "LastName": "Lombardi",
   "Phone": "333 3472757",
   "Email": "lomb45@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 7,
   "FirstName": "Rebecca",
   "LastName": "Marman",
   "Phone": "0044 7881 587368",
   "Email": "rebeccamarman@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 8,
   "FirstName": "Hubert",
   "LastName": "Cassel",
   "Phone": "07768 223941",
   "Email": "h.cassell@sky.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 9,
   "FirstName": "Fiore",
   "LastName": "Flaim",
   "Phone": "0039 333 2066576",
   "Email": "fiore1119@virgilio.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No English"
 },
 {
   "RecordID": 10,
   "FirstName": "Cesco",
   "LastName": "Dalla Rosa",
   "Phone": "0039 335 1245912",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 11,
   "FirstName": "Rosanna",
   "LastName": "Dapueto",
   "Phone": "0039 010 3471568",
   "Email": "info@rosannadapueto.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Limited english"
 },
 {
   "RecordID": 12,
   "FirstName": "Michael and Nini",
   "LastName": "Lustig",
   "Phone": "0039 347 9046735 IT",
   "Email": "mlustig@me.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Like to use Whatsapp and not email"
 },
 {
   "RecordID": 13,
   "FirstName": "Franco",
   "LastName": "Tartaro",
   "Phone": "0039 335 8043469",
   "Email": "tartarofranco@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 14,
   "FirstName": "Geraldina",
   "LastName": "Giovanoni",
   "Phone": "335 7989844",
   "Email": "info@stazzoluciaccaru.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 15,
   "FirstName": "Maria",
   "LastName": "Muzzurru",
   "Phone": "0039 348 2313475",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No engiish - calls or texts only"
 },
 {
   "RecordID": 16,
   "FirstName": "Franco",
   "LastName": "",
   "Phone": "0039 331 7978879",
   "Email": "fc@sportclinic.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 17,
   "FirstName": "Cristina",
   "LastName": "",
   "Phone": "0039 349 2115473",
   "Email": "kristinfede@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 18,
   "FirstName": "Luciano",
   "LastName": "Fresi",
   "Phone": "0039 347 4384683",
   "Email": "fresicostruzionisas@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No English"
 },
 {
   "RecordID": 19,
   "FirstName": "Christoph",
   "LastName": "Wiechart",
   "Phone": "",
   "Email": "Christoph.wiechert@disegno.de",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 20,
   "FirstName": "Maria Grazia",
   "LastName": "Slunder",
   "Phone": "0039 393 3949363\t\t",
   "Email": "loskina@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 21,
   "FirstName": "Roberto",
   "LastName": "Vicini",
   "Phone": "0039 3356357507 roberto",
   "Email": "roberto@studiolegalevicini.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english\nbarbara - daughter - english speaker 335 6660708"
 },
 {
   "RecordID": 22,
   "FirstName": "Daniela",
   "LastName": "Booking office",
   "Phone": "0039 392 970 33 83",
   "Email": "reception@hotelportopiccolo.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 23,
   "FirstName": "Bonaria",
   "LastName": "Filigheddu",
   "Phone": "",
   "Email": "info@hotelvilladelgolfo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Owner of Villa del Golfo\nYou can talk to Cinzia and Emidia at hotel for bookings"
 },
 {
   "RecordID": 24,
   "FirstName": "Max",
   "LastName": "Tinelli",
   "Phone": "0039 335 5892972",
   "Email": "max.tinelli@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "www.holidaylettings.it\nID CLIENTE: 616133\nIndirizzo email o ID cliente: immobiliareantei@gmail.com\nPassword: chioppi67\nhttp://www.tripadvisor.com/VacationRentalReview-g775994-d5772789-Appartamento_a_Porto_Rafael-Porto_Rafael_Province_of_Olbia_Tempio_Sardinia.html  \n\n\n\n\n"
 },
 {
   "RecordID": 25,
   "FirstName": "Delphina",
   "LastName": "",
   "Phone": "",
   "Email": "booking@delphina.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 26,
   "FirstName": "Francesco",
   "LastName": "Depperu",
   "Phone": "335 377840  Francesco",
   "Email": "info@capriccioli.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Francesco Depperu 335 377840 owner\nElisabetta and Mauro on reception - all good english.\nElisabetta (winter reservations) 349 8867725"
 },
 {
   "RecordID": 27,
   "FirstName": "Tenuta Pilastru",
   "LastName": "",
   "Phone": "",
   "Email": "info@tenutapilastru.it",
   "Town": "Arzachena",
   "Postcode": "7021",
   "Address": "Str Arzachena\nBassacutena, km 5 - 07021 ",
   "Notes": ""
 },
 {
   "RecordID": 28,
   "FirstName": "Marino ",
   "LastName": "Campus",
   "Phone": "331 5374018 (Marino)",
   "Email": "f.o.manager@calacuncheddi.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 29,
   "FirstName": "Cala Luna",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelcalaluna.net",
   "Town": "Cala Gonone",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 30,
   "FirstName": "Daniela ",
   "LastName": "Desogus",
   "Phone": "",
   "Email": "reception@hotelportopiccolo.com",
   "Town": "Baia Sardinia",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 31,
   "FirstName": "Donato",
   "LastName": "Podda",
   "Phone": "",
   "Email": "donpodda@tin.it",
   "Town": "Liscia di Vacca",
   "Postcode": "",
   "Address": "",
   "Notes": "English spoken"
 },
 {
   "RecordID": 32,
   "FirstName": "Carlo",
   "LastName": "",
   "Phone": "",
   "Email": "info@lantanaresort.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "English spoken"
 },
 {
   "RecordID": 33,
   "FirstName": "Italy to Rent - Luana",
   "LastName": "Zangarelli",
   "Phone": "+393339692517",
   "Email": "info@italytorent.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Casale Condotti\nhttps://calendar.google.com/calendar/embed?src=italytorent.com_k5n2q8onbpjs1va1fed1jnfj6g%40group.calendar.google.com&ctz=Europe/Rome\n\nVilla Il Convento\nhttps://calendar.google.com/calendar/embed?src=italytorent.com_cr700ka968gs29577l14hoot44%40group.calendar.google.com&ctz=Europe/Rome \n\nVilla Lavanda\nhttps://calendar.google.com/calendar/embed?src=italytorent.com_de1b15hhrof8bog2pmbj1486lo%40group.calendar.google.com&ctz=Europe/Rome\n\nVilla Lavanda\nhttps://calendar.google.com/calendar/embed?src=italytorent.com_o8epbd9mpupnriie98nnj5amts%40group.calendar.google.com&ctz=Europe/Rome\n\nVilla Valentino\nhttps://calendar.google.com/calendar/embed?src=italytorent.com_760rvdphka69sepj21f5ciekf0%40group.calendar.google.com&ctz=Europe/Rome\n\n"
 },
 {
   "RecordID": 34,
   "FirstName": "Liza",
   "LastName": "Bruce",
   "Phone": "Liza UK - 07979502172",
   "Email": "lizabruce@aol.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Liza Bruce and Nicholas Alvis Vega.\n+ 39 329 611 5962 Domenico caretaker\ndomenicoben@gmail.com\n\n"
 },
 {
   "RecordID": 35,
   "FirstName": "Francesca Valeriana",
   "LastName": "",
   "Phone": "+39347.6540194",
   "Email": "francescavalerianiarchitetto@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "http://www.homeaway.it/affitto-vacanze/p1004701#calendar"
 },
 {
   "RecordID": 36,
   "FirstName": "Giovan Battista ",
   "LastName": "Brogi",
   "Phone": "335 5258201 - Chiara",
   "Email": "giovanbattistabrogi@virgilio.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Giovan Battista Brogi\n00393337221496 - Marsia\nBenito - 333 9497065\n00393337221496 - Marsia\n07973513205 or 01626 870565 - Chiara - 335 5258201 \n\n"
 },
 {
   "RecordID": 37,
   "FirstName": "David Brenner",
   "LastName": "",
   "Phone": "+39 3662044567",
   "Email": "david@villasfor2.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 38,
   "FirstName": "test owner",
   "LastName": "banana",
   "Phone": "4.47754E+11",
   "Email": "",
   "Town": "newmarket",
   "Postcode": "cb88ll",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 39,
   "FirstName": "Vincent (GEKO)",
   "LastName": "de Cat",
   "Phone": "333 4497886",
   "Email": "vdecat@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Angel\nAgrumeto\nLa Botte\nLa Corte\nTemple"
 },
 {
   "RecordID": 40,
   "FirstName": "Madeline",
   "LastName": "",
   "Phone": "",
   "Email": "madeline@hotelleone.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 41,
   "FirstName": "Ian and Bob",
   "LastName": "",
   "Phone": "+39 3472 647680",
   "Email": "info@casaldeifichi.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 42,
   "FirstName": "Borgo San Marco",
   "LastName": "",
   "Phone": "0039 080 4395757",
   "Email": "info@borgosanmarco.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 43,
   "FirstName": "Paolo and Leonie",
   "LastName": "",
   "Phone": "+393384331573",
   "Email": "larascina@inwind.it",
   "Town": "Ostuni",
   "Postcode": "720017 Brindisi",
   "Address": "Masseria La Rascina\nStrada Provinciale 19\nRosamarina",
   "Notes": "Taxi man Angelo - 330964927"
 },
 {
   "RecordID": 44,
   "FirstName": "Mauro",
   "LastName": "",
   "Phone": "+393270937630",
   "Email": "booking@palazzoguglielmo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 45,
   "FirstName": "Benedetta Pasanisi Parma and Mario Parma",
   "LastName": "",
   "Phone": "0039 368 3739551",
   "Email": "masserialepezzate@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Masseria Le Pezzate\nTraversa Gallipolo snc\n73024 Maglie (LE)",
   "Notes": ""
 },
 {
   "RecordID": 46,
   "FirstName": "Canne Bianche",
   "LastName": "",
   "Phone": "",
   "Email": "reservations@cannebianche.com",
   "Town": "",
   "Postcode": "",
   "Address": "CANNE BIANCHE BEACH HOTEL & SPA\nVia Appia 32 - 72010 Torre Canne di Fasano (Brindisi) - Apulia ITALY",
   "Notes": "General info:\ninfo@cannebianche.com\n"
 },
 {
   "RecordID": 47,
   "FirstName": "Claudia and Franco",
   "LastName": "",
   "Phone": "+39 368261188",
   "Email": "fchiarpei@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Claudia and Franco\nContrada Cicerone s/n \nOstuni 72017 (BR)",
   "Notes": "renatamccabe@libero.it \n0039 3381692533\nRenata - new number - 3249959372\n\ndaughter in London - Clara - 0757001603\n\nTrullo Iduna +39 0804448934\nClaudia's Mobile +39 368261188\nFranco's Mobile +39 3358095657\nrenatamccabe@libero.it \n0039 3381692533\nRenata - new number - 3249959372\n\n\n"
 },
 {
   "RecordID": 48,
   "FirstName": "Prue Lane",
   "LastName": "",
   "Phone": "07850 123101",
   "Email": "pruelane@hotmail.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Rosa - property manager +39 330 553 340"
 },
 {
   "RecordID": 49,
   "FirstName": "Suzanne and Nicola",
   "LastName": "Wilson and Cirella",
   "Phone": "39-331-113-1783 ",
   "Email": "wilson.s.m@sympatico.ca",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "https://www.holidaylettings.it/case-vacanze/ostuni/1463102\n\nProperty manager - Pina’s mobile:39-333-758-3097 email: capinare@libero.it\n"
 },
 {
   "RecordID": 50,
   "FirstName": "Ivan ",
   "LastName": "dal' Olio",
   "Phone": "345 4950949",
   "Email": "ivandallolio@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Bookings and enquiries to:\ninfo@tenutailcavaliereditalia.it\n"
 },
 {
   "RecordID": 51,
   "FirstName": "Anna and Alessandro",
   "LastName": "",
   "Phone": "333 8506867",
   "Email": "anna@villaroncovisi.it",
   "Town": "",
   "Postcode": "",
   "Address": "Villa dell' Angelo\nVilla Il Cerritoio\nVilla Montedomini\nVilla Roncovisi",
   "Notes": "Anna \nwww.tuscanholidayplus.it/booking\nLogin: essential\nPassword: italy"
 },
 {
   "RecordID": 52,
   "FirstName": "Anna Maria",
   "LastName": "Marino",
   "Phone": "339 7471124",
   "Email": "annamaria.marino@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "Trullo Anna",
   "Notes": "no English"
 },
 {
   "RecordID": 53,
   "FirstName": "Fabrizio ",
   "LastName": "Vanni",
   "Phone": "+39 349 7560403",
   "Email": "agrimusic2@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Fabrizio and Ivana\nSan Martino 10\nCivitella in Val di Chiana\n52040 Arezzo",
   "Notes": "https://www.airbnb.co.uk/rooms/8360644"
 },
 {
   "RecordID": 54,
   "FirstName": "Giuseppe ",
   "LastName": "Baldetti",
   "Phone": "+393334001234",
   "Email": "info@villasenaia.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "http://www.bookingcalendar.info/56890"
 },
 {
   "RecordID": 55,
   "FirstName": "Licia",
   "LastName": "Dimascio",
   "Phone": "347 7880140",
   "Email": "liciadima@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 56,
   "FirstName": "Cesco",
   "LastName": "dalla Rosa",
   "Phone": "335 1245912",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english and only telephone contact."
 },
 {
   "RecordID": 57,
   "FirstName": "Maria Grazia",
   "LastName": "Pilo",
   "Phone": "393 3949363",
   "Email": "loskina@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 58,
   "FirstName": "Paolo",
   "LastName": "Manca",
   "Phone": "0044 7890 278709",
   "Email": "paolomanca13@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 59,
   "FirstName": "Franco",
   "LastName": "tartaro",
   "Phone": "335 8043469",
   "Email": "tartarofranco@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 60,
   "FirstName": "Giuseppe",
   "LastName": "Verdoni",
   "Phone": " 0044 7530309442",
   "Email": "guv201@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "email best way to contact him "
 },
 {
   "RecordID": 61,
   "FirstName": "Giovanna ",
   "LastName": "Salerno",
   "Phone": "335 7695122",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 62,
   "FirstName": "Giovanna",
   "LastName": "",
   "Phone": "",
   "Email": "info@sugologone.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Bastiano - reception manager"
 },
 {
   "RecordID": 63,
   "FirstName": "Myo Hotel",
   "LastName": "",
   "Phone": "",
   "Email": "frontofficehrs@roccesarde.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Paolo Tanini - front office"
 },
 {
   "RecordID": 64,
   "FirstName": "Is Morus",
   "LastName": "",
   "Phone": "",
   "Email": "info@ismorus.com",
   "Town": "Santa Margherita di Pula",
   "Postcode": "9010",
   "Address": "km 37,400 ",
   "Notes": "Manola - bookings"
 },
 {
   "RecordID": 65,
   "FirstName": "Jimmy",
   "LastName": "Millard",
   "Phone": "07971 571117",
   "Email": "jimmy@nunleyfarm.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 66,
   "FirstName": "Christoph",
   "LastName": "Wiechert",
   "Phone": "4.91727E+11",
   "Email": "Christoph.wiechert@disegno.de",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 67,
   "FirstName": "mario",
   "LastName": "Cioffi",
   "Phone": "",
   "Email": "info@hotel-cormoran.com",
   "Town": "Villasimius",
   "Postcode": "9049",
   "Address": "Via del Porto 37\nLocalita Campus",
   "Notes": ""
 },
 {
   "RecordID": 68,
   "FirstName": "Cristina",
   "LastName": "Gianni Fresi",
   "Phone": "349 2115473",
   "Email": "kristinfede@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 69,
   "FirstName": "Baja Hotels",
   "LastName": "Marco Bongiovanni",
   "Phone": "",
   "Email": "info@hotelinuraghi.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "\nSales Giulia Vizilio 0789 99006\ngiulia@bajahotels.it"
 },
 {
   "RecordID": 70,
   "FirstName": "Le Ginestre",
   "LastName": "",
   "Phone": "",
   "Email": "MKT@leginestrehotel.com",
   "Town": "Porto Cervo",
   "Postcode": "",
   "Address": "",
   "Notes": "direzione@leginestrehotel.com\nNew manager 2018 Francesco Sanna"
 },
 {
   "RecordID": 71,
   "FirstName": "Petra Segreta",
   "LastName": "",
   "Phone": " 366 2287885",
   "Email": "booking@petrasegretaresort.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Roberto Fioravanti\nManager - Front Office & Reservations\nbooking@petrasegretaresort.com"
 },
 {
   "RecordID": 72,
   "FirstName": "Cala Luna",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelcalaluna.net",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 73,
   "FirstName": "Lantana",
   "LastName": "",
   "Phone": "",
   "Email": "info@lantanaresort.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Carlo - Manager"
 },
 {
   "RecordID": 74,
   "FirstName": "Giuseppe and Alessandra",
   "LastName": "",
   "Phone": "",
   "Email": "info@baiadellepalme.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Alesssandra (sister)"
 },
 {
   "RecordID": 75,
   "FirstName": "Alessandro",
   "LastName": "",
   "Phone": "39 393 9009255 ",
   "Email": "info@residencerivaazzurra.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 76,
   "FirstName": "Laura ",
   "LastName": "Rixi",
   "Phone": "348 2444415 o 329 2903288",
   "Email": "lorenzo.rixi@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 77,
   "FirstName": "Antonella",
   "LastName": "Bernardini",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 78,
   "FirstName": "betta",
   "LastName": "penacchi",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 79,
   "FirstName": "Julie",
   "LastName": "",
   "Phone": "0044 7947 275384",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 80,
   "FirstName": "Salvatore ",
   "LastName": "Valleri",
   "Phone": "329 4924380",
   "Email": "studiovalleri@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 81,
   "FirstName": "Umberto",
   "LastName": "",
   "Phone": "333 3137343",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english"
 },
 {
   "RecordID": 82,
   "FirstName": "Michele",
   "LastName": "Pileri",
   "Phone": "328 8007801",
   "Email": "davipiri@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "no english\nemail is of son - Davide"
 },
 {
   "RecordID": 83,
   "FirstName": "Michelle",
   "LastName": "Comoy",
   "Phone": "",
   "Email": "Mrm-torica@orange.fr",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 84,
   "FirstName": "Giada",
   "LastName": "Castelli",
   "Phone": "347 4326493",
   "Email": "giada@tipografico.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 85,
   "FirstName": "Chrissie",
   "LastName": "Lang",
   "Phone": "",
   "Email": "chrissie@casasangabriel.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 86,
   "FirstName": "Chrissie",
   "LastName": "Lang",
   "Phone": "",
   "Email": "chrissie@casasangabriel.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 87,
   "FirstName": "Rolando",
   "LastName": "Stein",
   "Phone": "",
   "Email": "stein.rolando@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 88,
   "FirstName": "Masseria Montenapoleone",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriamontenapoleone.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Giuliano - owner\nDoriana - reception\nMasseria Montenapoleone\nC.da Bicocca (Via delle Croci), N° 8\n72010 Pezze di Greco (BR)\nPuglia\nITALY"
 },
 {
   "RecordID": 89,
   "FirstName": "Ricardo",
   "LastName": "",
   "Phone": "",
   "Email": "info@alfieri9.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 90,
   "FirstName": "Alessandro ",
   "LastName": "Gualtieri ",
   "Phone": "",
   "Email": "fattoria@artimino.com;hotel@artimino.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 91,
   "FirstName": "Carole",
   "LastName": "",
   "Phone": "",
   "Email": "info@trulliresidence.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Contrada Trito 292\n70010\nLocorontondo\nBA\n"
 },
 {
   "RecordID": 92,
   "FirstName": "Andrea ",
   "LastName": "Scordello",
   "Phone": "",
   "Email": "info@masseriagialli.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "marina and Marcello (owners) - no english\nAndrea Scordello - manager - english"
 },
 {
   "RecordID": 93,
   "FirstName": "Casa D'Autore",
   "LastName": "",
   "Phone": "",
   "Email": "info@casadautore.it",
   "Town": "",
   "Postcode": "",
   "Address": "Corso Mazzini 134\nOstuni (BR)",
   "Notes": "Anny\n"
 },
 {
   "RecordID": 94,
   "FirstName": "Masseria il Mandorlo Fiorito",
   "LastName": "",
   "Phone": "",
   "Email": "pinom944@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 95,
   "FirstName": "Deborah ",
   "LastName": "Nolan",
   "Phone": "",
   "Email": "deborahmnolan@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 96,
   "FirstName": "Gino",
   "LastName": "Notarangelo",
   "Phone": "",
   "Email": "info@gattarella.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "all requests to go to mariella & info:\nmariella.cavaliere@gattarella.it\ninfo@gattarella.it\n\n0884 703616\nmariapina.caruso@gattarella.it \n\nGino - manager\ngino.notarangelo@gattarella.it\n\nMaria Rosa - Ginos assistant & wife\nmrdp@gattarella.it \n\nMauro Coricelli - Commerical manager\n\nMario d'Amore - communication manager\nmario.damore@gattarella.it\n\n\nJulie Holberry - sales director\njulie.h@gattarella.it 079790978989"
 },
 {
   "RecordID": 97,
   "FirstName": "Giancarlo and Antonella",
   "LastName": "",
   "Phone": "",
   "Email": "fuoridalmondonoci@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Zona D 19/A\nStrada Vicinale Giannevolte Scorso\n70015 Noci",
   "Notes": ""
 },
 {
   "RecordID": 98,
   "FirstName": "Masseria Torre Maizza",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriatorremaizza.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Savelletri di Fasano, Bari, Puglia."
 },
 {
   "RecordID": 99,
   "FirstName": "Masseria Torre Coccaro",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriatorrecoccaro.com",
   "Town": "",
   "Postcode": "",
   "Address": "Savelletri di Fasano, Bari, Puglia",
   "Notes": ""
 },
 {
   "RecordID": 100,
   "FirstName": "Marta",
   "LastName": "Marati",
   "Phone": "",
   "Email": "info@palazzogorgoni.it",
   "Town": "",
   "Postcode": "",
   "Address": "Via Idomeneo, 38. \n73100 - LECCE - SALENTO ",
   "Notes": ""
 },
 {
   "RecordID": 101,
   "FirstName": "Vivosa Apulia Resort ",
   "LastName": "",
   "Phone": "",
   "Email": "booking@vivosaresort.com",
   "Town": "",
   "Postcode": "",
   "Address": "Via Vicinale Fontanelle\nCasella Postale 106\nI-73059 Marina di Ugento (LE)",
   "Notes": "Lucia Palese - booking office"
 },
 {
   "RecordID": 102,
   "FirstName": "Trullo Pietra ",
   "LastName": "",
   "Phone": "",
   "Email": "darioneglia@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Dario - 0039/3407145900\nProperty manager - Renata\n3249959372 and 3381692533 \n"
 },
 {
   "RecordID": 103,
   "FirstName": "Melania ",
   "LastName": "Baccaro",
   "Phone": "",
   "Email": "melania.baccaro@alice.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "sister of Ambrogio\nambrogio 366 1041958 \nmelania 368 3707095"
 },
 {
   "RecordID": 104,
   "FirstName": "La Fiermontina ",
   "LastName": "",
   "Phone": "",
   "Email": "info@lafiermontina.com",
   "Town": "",
   "Postcode": "",
   "Address": "P.tta Scipione De Summa 4\n73100 Lecce (LE) Italia",
   "Notes": "La Fiermontina - Urban Resort in Lecce\n\nP.tta Scipione De Summa 4\n73100 Lecce (LE) Italia\n\nTel. +39 0832 302481\ncell. +39 3426156248\n\ninfo@lafiermontina.com\nwww.lafiermontina.com\n\n"
 },
 {
   "RecordID": 105,
   "FirstName": "Don Ferrante ",
   "LastName": "",
   "Phone": "",
   "Email": "info@donferrante.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Cell: 393 3501373\nCell: 393 3654652\n\n"
 },
 {
   "RecordID": 106,
   "FirstName": "Rico and Tracey",
   "LastName": "Lamarra",
   "Phone": "",
   "Email": "ricolamarra@hotmail.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "House Manager: Ottavio -Rico's Brother\n Ottavio +39 340 8397034 and +39 080 4449733  "
 },
 {
   "RecordID": 107,
   "FirstName": "Karita ",
   "LastName": "Massara",
   "Phone": "",
   "Email": "karitamassara@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 108,
   "FirstName": "Francesca ",
   "LastName": "",
   "Phone": "",
   "Email": "Francesca.dibari81@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "No english."
 },
 {
   "RecordID": 109,
   "FirstName": "Ostuni Rosa Marina Resort",
   "LastName": "",
   "Phone": "",
   "Email": "info@ostunirosamarinaresort.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 110,
   "FirstName": "Richard",
   "LastName": "Evans ",
   "Phone": "07711 033 325.",
   "Email": "revansconsultancy@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "at home on 0208 977 3124 or mobile 07711 033 325."
 },
 {
   "RecordID": 111,
   "FirstName": "Athena",
   "LastName": "McAlpine",
   "Phone": "07736 362 328 or 07738694504",
   "Email": "mcalpine@convento.co.uk;athenamalpass@yahoo.com",
   "Town": "",
   "Postcode": "",
   "Address": "Il Convento di Santa Maria di Constantinopoli\nVia Convento\n73030 Marittima di Diso\n(LE) Puglia\nItaly",
   "Notes": "Pierluigi  +39 34 06 14 12 38  pdpigi@hotmail.it\n\n\n"
 },
 {
   "RecordID": 112,
   "FirstName": "Palazzo Margherita",
   "LastName": "",
   "Phone": "",
   "Email": "sales@palazzomargherita.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "rossella@palazzomargherita.com - General Manager\n\nMaria Rosario\ninfo@palazzomargherita.com  - use this for enquiries"
 },
 {
   "RecordID": 113,
   "FirstName": "Adriana and Manuela Aloisi",
   "LastName": "",
   "Phone": "",
   "Email": "Info@santamartalecce.com",
   "Town": "",
   "Postcode": "",
   "Address": "Santa Marta Suites \nVia Orsini del Balzo 60 - 73100 Lecce ",
   "Notes": "adriana.aloisi@hotmail.it\ninfo@santamartalecce.it "
 },
 {
   "RecordID": 114,
   "FirstName": "Timo ",
   "LastName": "Bosma",
   "Phone": "",
   "Email": "tbosma@interbos.nl",
   "Town": "",
   "Postcode": "",
   "Address": "Gemaalweg 19\n5221 CH ’s-Hertogenbosch\nThe Netherlands\n",
   "Notes": ""
 },
 {
   "RecordID": 115,
   "FirstName": "Sarah",
   "LastName": "Mussenden",
   "Phone": "07710 283798 Sarah ",
   "Email": "sarah.mussenden@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Woodside House, Chenies, Rickmansworth, Hertfordshire, WD3 6EU",
   "Notes": "paul.mussenden@btgplc.com"
 },
 {
   "RecordID": 116,
   "FirstName": "Nicoletta",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelmontesarago.it",
   "Town": "",
   "Postcode": "",
   "Address": "C.so Mazzini, 233 – 72017 Ostuni(Br)",
   "Notes": ""
 },
 {
   "RecordID": 117,
   "FirstName": "Trullo Pesca",
   "LastName": "",
   "Phone": "",
   "Email": "trullipesca@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Via Alfonso Pomes, 17\nOstuni\n",
   "Notes": ""
 },
 {
   "RecordID": 118,
   "FirstName": "Gianluigi ",
   "LastName": "Mondaini",
   "Phone": "",
   "Email": "g.mondaini@univpm.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "GL lives in Ancona"
 },
 {
   "RecordID": 119,
   "FirstName": "Masseria Potenti",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriapotenti.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Noemi \n\nChiara also deals with bookings on the number below.\n\n"
 },
 {
   "RecordID": 120,
   "FirstName": "Naturalis",
   "LastName": "",
   "Phone": "349 8251363",
   "Email": "info@naturalisbioresort.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Manager Luigi Anfosso\n389 1317856\nmanager@naturalisbioresort.com\n\nHotel cell 349 8251363\nDomenico Scordari"
 },
 {
   "RecordID": 121,
   "FirstName": "Masseria Bagnara",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriabagnara.it",
   "Town": "",
   "Postcode": "",
   "Address": "Strada Provinciale 125 - Lizzano (TA) ",
   "Notes": "Manager Francesco Benedetto\n388 97 90 708 "
 },
 {
   "RecordID": 122,
   "FirstName": "Serena ",
   "LastName": "Buttiglione",
   "Phone": "",
   "Email": "seresere@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 123,
   "FirstName": "Luisa ",
   "LastName": "Donati",
   "Phone": "+39 339 4016247",
   "Email": "eventi@montestigliano.it",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Pipistrelli",
   "Notes": ""
 },
 {
   "RecordID": 124,
   "FirstName": "Casa Calandra ",
   "LastName": "",
   "Phone": "7736770898",
   "Email": "martinbrett@live.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Martin and Elizabeth Brett\n4 Beechrow\nChurch Road\nHam\nRichmond TW10 5HE\n\nelizapbrett@tiscali.co.uk - Martin Brett \nmartinbrett@live.co.uk (best one to use)\n\nAntonio - builder - 340 413 4825\nannieinpuglia@hotmail.com"
 },
 {
   "RecordID": 125,
   "FirstName": "Trulli Country Farmhouse",
   "LastName": "",
   "Phone": "07941622492 ",
   "Email": "galati.claudio@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 126,
   "FirstName": "Helena and Glen",
   "LastName": "Winter",
   "Phone": "07967 168369 - temporary number 07956328769",
   "Email": "helena.sukfan@googlemail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Masseria Cupina, \nContrada Angelo Di Maglie, \n72013 Ceglie Messapica (Br), Italy.\n",
   "Notes": ""
 },
 {
   "RecordID": 127,
   "FirstName": "Foresteria Palermo",
   "LastName": "Alessandro Failla",
   "Phone": "+39 0925 1955460",
   "Email": "laforesteriapalermo@planeta.it",
   "Town": "",
   "Postcode": "",
   "Address": "Foresteria apartments",
   "Notes": ""
 },
 {
   "RecordID": 128,
   "FirstName": "Casa dei Mercanti",
   "LastName": "",
   "Phone": "",
   "Email": "info@casadeimercanti.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 129,
   "FirstName": "Greg and Natasha",
   "LastName": "Shirley",
   "Phone": "",
   "Email": "greg.shirley@permira.com",
   "Town": "",
   "Postcode": "",
   "Address": "Trullo Elio",
   "Notes": "Pino\n+39 080 4447278\n00 39 329 9870243\n"
 },
 {
   "RecordID": 130,
   "FirstName": "Palazzo Mosco Inn",
   "LastName": "",
   "Phone": "",
   "Email": "info@palazzomoscoinn.it",
   "Town": "",
   "Postcode": "",
   "Address": "73014 Gallipoli (LE) - Italy\nVia Micetti, 26\n",
   "Notes": "Michele"
 },
 {
   "RecordID": 131,
   "FirstName": "Elisabetta",
   "LastName": "Ianucci",
   "Phone": "00 39 335 5289160",
   "Email": "betta_spring@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 132,
   "FirstName": "Metato",
   "LastName": "Stefano Viviani",
   "Phone": "0039 338 6748641 or 0049 (0) 177 18672251",
   "Email": "stefanovivianiarchitetto@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 133,
   "FirstName": "Hotel Sant' Angelo",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelsantangelosassi.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 134,
   "FirstName": "Antonio",
   "LastName": "",
   "Phone": "",
   "Email": "antonioromanazzi1@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "Casa d' Cicciloz",
   "Notes": ""
 },
 {
   "RecordID": 135,
   "FirstName": "Sally ",
   "LastName": "Ball",
   "Phone": "07899 663970",
   "Email": "sallyballhome@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Trullo Callisto",
   "Notes": ""
 },
 {
   "RecordID": 136,
   "FirstName": "Valle dell' Idro",
   "LastName": "",
   "Phone": "",
   "Email": "info@otrantohotel.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 137,
   "FirstName": "Sophie Tourner",
   "LastName": "",
   "Phone": "",
   "Email": "info@casavitaostuni.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Vita ",
   "Notes": "Holiday Lettings, property 80219 \ncostanza polidori puglia-sos@msn.com\nSophie & Werner Tournier [huygentournier@telenet.be]\nSophie - 0032 473470394\nWerner - 0032 479 978321"
 },
 {
   "RecordID": 138,
   "FirstName": "Ted",
   "LastName": "Gagnon",
   "Phone": "",
   "Email": "tpgagnon64@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Trullo Capitolo\n11631 Springhouse Place\nReston, VA  20194",
   "Notes": "Ted in Italy - 39 3396215711\ntgagnon@arista.com (work address)\n\ncasachecanta@yahoo.com but\nuse this one \ntpgagnon64@gmail.com\n"
 },
 {
   "RecordID": 139,
   "FirstName": "Trullo Lontano",
   "LastName": "",
   "Phone": "",
   "Email": "gaylerobling@yahoo.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "\nElisa tel: 0039 3687648043\nhome 0039 0831 332769"
 },
 {
   "RecordID": 140,
   "FirstName": "Tenuta Monacelli",
   "LastName": "",
   "Phone": "",
   "Email": "booking@tenutamonacelli.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Maria\nMaria Elena - new to sales in 2017"
 },
 {
   "RecordID": 141,
   "FirstName": "I Trulli del Nonno Michele",
   "LastName": "",
   "Phone": "",
   "Email": "info@trullidelnonnomichele.com",
   "Town": "",
   "Postcode": "",
   "Address": "Thomas (Tommaso)\nVia Capitolo Colucci Zona B, 142\n74015 Martina Franca \n(TA)\nItalia",
   "Notes": ""
 },
 {
   "RecordID": 142,
   "FirstName": "Terra Sessana",
   "LastName": "",
   "Phone": "",
   "Email": "info@terrasessana.it",
   "Town": "",
   "Postcode": "",
   "Address": "Contrada Sessana Piccola\nOstuni, BR - 72017\nPuglia, Italy\n\n",
   "Notes": "availability on website  \nmario and Laura\nhttp://www.terrasessana.it/en/availability\n+39 366 193 66 06 +39 333 618 01 47 +39 347 606 07 84 Laura\n\n"
 },
 {
   "RecordID": 143,
   "FirstName": "Trullo San Pietro",
   "LastName": "",
   "Phone": "+ 39 338 5797119",
   "Email": "melissa@revolution-films.com;crimmimmobiliare@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Melissa Parmenter\n6 Albany Road\nN4 4 RJ\n\n0039 3335368060 / 07775 751617- Christina (caretaker)\nMobile: + 39 338 5797119\n\n"
 },
 {
   "RecordID": 144,
   "FirstName": "Tenuta Cento Porte ",
   "LastName": "",
   "Phone": "",
   "Email": "tenutacentoporte@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Simona has gone - not sure of the new person."
 },
 {
   "RecordID": 145,
   "FirstName": "Liscia di Vacca ",
   "LastName": "",
   "Phone": "",
   "Email": "donpodda@tin.it",
   "Town": "",
   "Postcode": "",
   "Address": "Residence Liscia di Vacca\nLocalità Liscia di Vacca – \n07021 Arzachena \nOT\nITALIA\n",
   "Notes": ""
 },
 {
   "RecordID": 146,
   "FirstName": "Arbatax Park",
   "LastName": "",
   "Phone": "",
   "Email": "paolo@arbataxpark.com",
   "Town": "",
   "Postcode": "",
   "Address": "Via  Capri 49/B\nArbatax 08048\nOG",
   "Notes": "Hotel Monte Turri and Cottage Hotel\n\nPaolo curridori (sales manager)\nGood english\n\nCottage Hotel reservations\nAngela Lecis\nprenotazioni@arbataxpark.com"
 },
 {
   "RecordID": 147,
   "FirstName": "Elena ",
   "LastName": "",
   "Phone": "",
   "Email": "vettagiovanna@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "elena Bonazzi"
 },
 {
   "RecordID": 148,
   "FirstName": "Villa Mosca",
   "LastName": "",
   "Phone": "",
   "Email": "booking@villamosca.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Silvia Sogos is the booking lady"
 },
 {
   "RecordID": 149,
   "FirstName": "Villa Leo",
   "LastName": "",
   "Phone": "",
   "Email": "immobsanpantaleo@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Antonio Azara\n\nAntonio and Rosella\n366 3801869\n333 7218485\n"
 },
 {
   "RecordID": 150,
   "FirstName": "Villa Barbarina",
   "LastName": "",
   "Phone": "",
   "Email": "info@villabarbarina.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 151,
   "FirstName": "Villa Franco",
   "LastName": "",
   "Phone": "",
   "Email": "Francesco.maturi@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Francesco Maturi"
 },
 {
   "RecordID": 152,
   "FirstName": "Hotel Catalunya ",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelcatalunya.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "we have a code on their web site for pricing:\n\nEssential2014"
 },
 {
   "RecordID": 153,
   "FirstName": "Colonna Grand Hotel Capo Testa",
   "LastName": "",
   "Phone": "",
   "Email": "capotesta@itihotels.it",
   "Town": "",
   "Postcode": "",
   "Address": "Loc. Capo Testa\n07028 Santa Teresa Gallura",
   "Notes": ""
 },
 {
   "RecordID": 154,
   "FirstName": "Hotel Ancora ",
   "LastName": "",
   "Phone": "",
   "Email": "info@hotelancora.info",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "\n Lot\nizzazione Ancora, 07040 Stintino"
 },
 {
   "RecordID": 155,
   "FirstName": "Villa Resort ",
   "LastName": "",
   "Phone": "",
   "Email": "info@villasresort.it",
   "Town": "",
   "Postcode": "",
   "Address": "Loc Santa Giusta\nCastiadas\n09040 CA",
   "Notes": "Rita booking "
 },
 {
   "RecordID": 156,
   "FirstName": "Villa Lestra",
   "LastName": "",
   "Phone": "",
   "Email": "info@villaangelica.net",
   "Town": "",
   "Postcode": "",
   "Address": "Via Veneto 25\n56037\nFabrica di Peccioli\nPisa",
   "Notes": ""
 },
 {
   "RecordID": 157,
   "FirstName": "Villa Andrea",
   "LastName": "",
   "Phone": "",
   "Email": "guidopoli32@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Guido Poli"
 },
 {
   "RecordID": 158,
   "FirstName": "Francigena",
   "LastName": "",
   "Phone": "",
   "Email": "villalafrancigena@live.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "posarelli under villa giulia, you can contact Giulia, daughter\n\nhttp://www.villalafrancigena.com/\n"
 },
 {
   "RecordID": 159,
   "FirstName": "Casa Alberta",
   "LastName": "",
   "Phone": "",
   "Email": "albertotabani@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Alberto Tabani"
 },
 {
   "RecordID": 160,
   "FirstName": "Poggio Pilella ",
   "LastName": "",
   "Phone": "",
   "Email": "poggiopilella@poggiallago.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Stefano Raimondi\n\n"
 },
 {
   "RecordID": 161,
   "FirstName": "Casa Il Melograno",
   "LastName": "",
   "Phone": "",
   "Email": "sabrinacambi@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Address -\nCasa Vacanze Il Melograno\nLoc. i Melagrani 31/A - Santa Lucia\n53037 San Gimignano (Siena) Italy\n ",
   "Notes": "Stefano Faraoni\n"
 },
 {
   "RecordID": 162,
   "FirstName": "Borgo Canonica",
   "LastName": "Maria",
   "Phone": "080 4448416",
   "Email": "amministrazione@borgocanonica.com",
   "Town": "",
   "Postcode": "",
   "Address": "Borgo Canonica\nC.da Minetta, 20 \n72014 Cisternino (BR) - ITALY",
   "Notes": ""
 },
 {
   "RecordID": 163,
   "FirstName": "Virginie",
   "LastName": "Allavena",
   "Phone": "328 7891184",
   "Email": "info@castellodigranarola.it",
   "Town": "Granarola",
   "Postcode": "",
   "Address": "Castello di Granarola\nVia Castello 1\nGranarola\nGradara\n",
   "Notes": ""
 },
 {
   "RecordID": 164,
   "FirstName": "Aldiola Country Resort ",
   "LastName": "",
   "Phone": "",
   "Email": "aldiolainfo@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Caterina\n"
 },
 {
   "RecordID": 165,
   "FirstName": "Le Capase Resort",
   "LastName": "Simona Grecco",
   "Phone": "347 7907836",
   "Email": "booking@lecapase.it",
   "Town": "Otranto",
   "Postcode": "73020",
   "Address": "Le Capase Resort\nVillaggio paradiso\nSanta Cesarea terme",
   "Notes": ""
 },
 {
   "RecordID": 166,
   "FirstName": "Casa Rafael ",
   "LastName": "",
   "Phone": "",
   "Email": "lguerrieri@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Signora Parodi (Dada)"
 },
 {
   "RecordID": 167,
   "FirstName": "Bella Vista ",
   "LastName": "",
   "Phone": "",
   "Email": "simone.farinola@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Simone Farinola.\nNo English."
 },
 {
   "RecordID": 168,
   "FirstName": "Hotel Gutkowski",
   "LastName": "",
   "Phone": "",
   "Email": "info@guthotel.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 169,
   "FirstName": "Locanda Sant' Andrea",
   "LastName": "",
   "Phone": "",
   "Email": "hotel@locandasantandrea.com",
   "Town": "",
   "Postcode": "",
   "Address": "Locanda Sant' Andrea\nVia Zara 36, 07026 San Pantaleo Olbia",
   "Notes": ""
 },
 {
   "RecordID": 170,
   "FirstName": "Manila ",
   "LastName": "Parisi",
   "Phone": "",
   "Email": "isira91@virgilio.it",
   "Town": "",
   "Postcode": "",
   "Address": "Scozilia",
   "Notes": ""
 },
 {
   "RecordID": 171,
   "FirstName": "Francesca ",
   "LastName": "Spadacini",
   "Phone": "",
   "Email": "taten2000@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "Trullo Tati",
   "Notes": "and Sergio Pascal"
 },
 {
   "RecordID": 172,
   "FirstName": "Relais Torre Marabino",
   "LastName": "",
   "Phone": "",
   "Email": "info@torremarabino.com;direzione@torremarabino.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Simona and Francesco\nhttps://db.tt/Ak5VhYpqDu\n\n "
 },
 {
   "RecordID": 173,
   "FirstName": "EREMO DELLA GIUBILIANA ",
   "LastName": "",
   "Phone": "Mobile 39 366 5799984",
   "Email": "booking@eremodellagiubiliana.com",
   "Town": "",
   "Postcode": "",
   "Address": "C.da Giubiliana - S.P. per Marina di Ragusa km 7,5 \n97100 Ragusa ",
   "Notes": "Giana or Angelo\n\nTel +39 0932 66911 or  Mobile 39 366 5799984"
 },
 {
   "RecordID": 174,
   "FirstName": "Villa Silvia ",
   "LastName": "",
   "Phone": "",
   "Email": "alessandrabonaccorsi@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Silvia and Torre Antica   \n\n",
   "Notes": "http://www.homeaway.it/affitto-vacanze/p473674  \n\nhttp://www.novasol.it/p/ISS477?S=2013&month=2013_2&wt.si_n=GoogleMiniBookingFlow"
 },
 {
   "RecordID": 175,
   "FirstName": "Casa del Sole",
   "LastName": "",
   "Phone": "",
   "Email": "antonellapadova@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "Lungomare Andrea Doria 46 ,\n97070\nMarina di Ragusa",
   "Notes": ""
 },
 {
   "RecordID": 176,
   "FirstName": "Monaci delle Terre Nere",
   "LastName": "",
   "Phone": "",
   "Email": "info@monacidelleterrenere.it",
   "Town": "",
   "Postcode": "",
   "Address": "Guido Alessandro\nRelais Monaci delle Terre Nere\nVia Monaci snc\n95019 Zafferana Etnea",
   "Notes": ""
 },
 {
   "RecordID": 177,
   "FirstName": "EH13",
   "LastName": "",
   "Phone": "",
   "Email": "eh13@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "Via S. Euplio, 13\nCatania (CT) 95124\nSalvatore",
   "Notes": ""
 },
 {
   "RecordID": 178,
   "FirstName": "Fabio",
   "LastName": "",
   "Phone": "",
   "Email": "fabiobocchieri@virgilio.it",
   "Town": "",
   "Postcode": "",
   "Address": "Fabio Bocchieri",
   "Notes": "The Beach House\nCasa Blu"
 },
 {
   "RecordID": 179,
   "FirstName": "Rosario",
   "LastName": "",
   "Phone": "",
   "Email": "info@lacasadelsole.com",
   "Town": "",
   "Postcode": "",
   "Address": "La Ganzaria\nSantacroce",
   "Notes": "lacasadelsole.com \n\nusername: sicily and the password: villa2014. \nwww.237.it/cds\nhttps://www.homeaway.co.uk/p65706\n\ninfo@lacasadelsole.com  villa@237.it "
 },
 {
   "RecordID": 180,
   "FirstName": "Giulia ",
   "LastName": "Di Vincenzo",
   "Phone": "",
   "Email": "giuliadivincenzo@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "La Suite andf Scuderia \n\n\nGiulia Di Vincenzo\nVia S.tenente G. Sapio, 7\n92027 Licata (AG)\n",
   "Notes": "Case Montesole"
 },
 {
   "RecordID": 181,
   "FirstName": "Isula Travel",
   "LastName": "",
   "Phone": "",
   "Email": "booking@isulatravel.com;direzione@torremarabino.com",
   "Town": "",
   "Postcode": "",
   "Address": "Corallo, delle Dune, delle Palme, Ispica & Corallo",
   "Notes": "Francesco - direzione@torremarabino.com\nEnzo - booking@isulatravel.com\nhttps://www.isulasicilia.com/listing/41"
 },
 {
   "RecordID": 182,
   "FirstName": "Masseria Susafa",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriasusafa.com",
   "Town": "",
   "Postcode": "",
   "Address": "Contrada Susafa \nPolizzi Generosa (PA)\n",
   "Notes": ""
 },
 {
   "RecordID": 183,
   "FirstName": "Il Giardino di Ballaro",
   "LastName": "",
   "Phone": "",
   "Email": "ilgiardinodiballaropalermo@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Valentina\nVia Porta di Castro 75/77, 90134 Palermo, Italia\n",
   "Notes": ""
 },
 {
   "RecordID": 184,
   "FirstName": "Casa Salina ",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Agnello Modica Maria\nC/O Francesca at Marabino"
 },
 {
   "RecordID": 185,
   "FirstName": "Fattoria Santa Vittoria ",
   "LastName": "",
   "Phone": "39 3701211372",
   "Email": "info@fattoriasantavittoria.net;marta@fattoriasantavittoria.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Owner Marta Niccolai\nTel. 0039  0575 66629 (office)\nMauro cell. 0039 3934410905\nCHECK AVAILABILITY on website\n\nTel. 0039  0575 66629 (office)\nMauro cell. 0039 3934410905 - Marta 39 3701211372"
 },
 {
   "RecordID": 186,
   "FirstName": "Masseria Rosella",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseria-rossella.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 187,
   "FirstName": "Casa del Pittore",
   "LastName": "",
   "Phone": "",
   "Email": "baldoni.davide@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Lorenzo\nLocalita Valecchia\nMontanare\nCortona\nArezzo\n52100",
   "Notes": ""
 },
 {
   "RecordID": 188,
   "FirstName": "Fattoria La Loggia ",
   "LastName": "",
   "Phone": "",
   "Email": "info@fattorialaloggia.com",
   "Town": "",
   "Postcode": "",
   "Address": "Ivana and Carolina\nVia Collina, 40 - \n50026 San Casciano in Val di Pesa\nLoc. Montefiridolfi  \nFlorence \nItaly",
   "Notes": ""
 },
 {
   "RecordID": 189,
   "FirstName": "Fiordaliso",
   "LastName": "",
   "Phone": "",
   "Email": "info@agrifiordaliso.com",
   "Town": "",
   "Postcode": "",
   "Address": "Fiordaliso\nVia La Croce, 12 - 06039 Bovara di Trevi - Perugia - Italy",
   "Notes": ""
 },
 {
   "RecordID": 190,
   "FirstName": "Lucio",
   "LastName": "Ianelli",
   "Phone": "",
   "Email": "lucioianelli65@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Ibla\nTerrazza sul Mare",
   "Notes": "http://www.homelidays.it/casa-vacanze/p6454265\nSame owner as Terrazze sul Mare \n\n\nhttps://www.homelidays.it/casa-vacanze/p1626018 \n\n\n\nhttp://www.homeaway.it/affitto-vacanze/p6581357"
 },
 {
   "RecordID": 191,
   "FirstName": "Ibla in Suite ",
   "LastName": "",
   "Phone": "",
   "Email": "info@iblainsuite.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Arturo and Antonella"
 },
 {
   "RecordID": 192,
   "FirstName": "Ibla Terrace Apartment ",
   "LastName": "",
   "Phone": "",
   "Email": "info@parcocavalonga.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Ludovico Peirce\nOwner\n"
 },
 {
   "RecordID": 193,
   "FirstName": "Luca Giannini ",
   "LastName": "Smurra",
   "Phone": "",
   "Email": "info@animeasud.it",
   "Town": "",
   "Postcode": "",
   "Address": "Kimiya and Casa Hortus \nVia S Lucia 9, MOdica\n",
   "Notes": "+39 348 4002975\n use this email once bookings have been made or any account queries - admin@animeasud.it"
 },
 {
   "RecordID": 194,
   "FirstName": "Villa Donata - Massimo",
   "LastName": "",
   "Phone": "3474534884",
   "Email": "cantinettadirignana@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Donata",
   "Notes": ""
 },
 {
   "RecordID": 195,
   "FirstName": "Rosado Rosadi",
   "LastName": "",
   "Phone": "Rosado - 0039 3339699004",
   "Email": "rosado@palazzorosadi.com",
   "Town": "",
   "Postcode": "",
   "Address": "Torre del Cielo",
   "Notes": ""
 },
 {
   "RecordID": 196,
   "FirstName": "Sicilia Casa Vacanza",
   "LastName": "",
   "Phone": "",
   "Email": "info@siciliacasavacanza.com",
   "Town": "",
   "Postcode": "",
   "Address": "\n\n\n\nScopello Properties\nMediterranean Services LLC\n1220 N. Market Street Suite 808\nDelaware in Wilmignton\n19801\nUSA",
   "Notes": "Scopello"
 },
 {
   "RecordID": 197,
   "FirstName": "Orietta",
   "LastName": "Paltrinieri",
   "Phone": "",
   "Email": "paltrinieri.orietta@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Valentina\nIl Tribbio\nIl Tribbio Due\nLa Capanna\nLa Consuma",
   "Notes": "Maria Federjica Vestrucci\n338 4044230  - owner - all booking through Orietta\nfedesorge@hotmail.com  (owner)"
 },
 {
   "RecordID": 198,
   "FirstName": "Geocharm",
   "LastName": "Marina - Marina Tarantino",
   "Phone": "0923 972122",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "Hotel Vallegrande\nContrada Vallegrande,\n90015 Cefalù (PA)",
   "Notes": "hotel@caposanvito.it \nVallegrande - info@hotelvallegrande.it - \n342 0011095\nBaglio la Porta - \nGeocharm\n\nMarina Tarantino or Vanessa\nBooking Office\n0923 972122\n342 0011095\n\n\n"
 },
 {
   "RecordID": 199,
   "FirstName": "La Scibina - Federica",
   "LastName": "",
   "Phone": "338 3824477",
   "Email": "info@lascibina.it",
   "Town": "",
   "Postcode": "",
   "Address": "La Scibina\nSignora Criscione\nVia Panareo 31\nMarina di Ragusa ",
   "Notes": ""
 },
 {
   "RecordID": 200,
   "FirstName": "Hotel Villa Angela ",
   "LastName": "",
   "Phone": "",
   "Email": "hotel@hotelvillaangela.com",
   "Town": "",
   "Postcode": "",
   "Address": "Via Leonardo Da Vinci s.n.\n98039 Taormina (ME0\nSicily\n",
   "Notes": ""
 },
 {
   "RecordID": 201,
   "FirstName": "La Gancia",
   "LastName": "",
   "Phone": "",
   "Email": "booking@lagancia.com",
   "Town": "",
   "Postcode": "",
   "Address": "Via Mura di Tramontana Ovest, 1 - Piazza Mercato d, 91100 Trapani, Italy ",
   "Notes": ""
 },
 {
   "RecordID": 202,
   "FirstName": "Cavalonga ",
   "LastName": "",
   "Phone": "",
   "Email": "info@parcocavalonga.it",
   "Town": "",
   "Postcode": "",
   "Address": "Relais Parco Cavalonga\nStrada Provinciale 80 km 3.200\n97100 Ragusa\n",
   "Notes": "Noemi"
 },
 {
   "RecordID": 203,
   "FirstName": "Casa Talia",
   "LastName": "",
   "Phone": "",
   "Email": "info@casatalia.it",
   "Town": "",
   "Postcode": "",
   "Address": "Marco",
   "Notes": ""
 },
 {
   "RecordID": 204,
   "FirstName": "La Foresteria",
   "LastName": "",
   "Phone": "",
   "Email": "planetaestate@planeta.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 205,
   "FirstName": "BB22",
   "LastName": "",
   "Phone": "+39 3357908733",
   "Email": "infobb22@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Massimo Palloni\n",
   "Notes": ""
 },
 {
   "RecordID": 206,
   "FirstName": "Palazzo del Sale ",
   "LastName": "",
   "Phone": "",
   "Email": "info@giuggiulena.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Sabrina and Giovanni"
 },
 {
   "RecordID": 207,
   "FirstName": "Cambiocavallo",
   "LastName": "",
   "Phone": "",
   "Email": "cambiocavallo@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 208,
   "FirstName": "Faccia a Mare ",
   "LastName": "",
   "Phone": "",
   "Email": "rosalbadellalbani@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Sig.ra Rosalba Dell’Albani"
 },
 {
   "RecordID": 209,
   "FirstName": "Punta Secca",
   "LastName": "",
   "Phone": "",
   "Email": "tittag@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Gianbattista Gambuzza"
 },
 {
   "RecordID": 210,
   "FirstName": "Geocharme",
   "LastName": "",
   "Phone": "",
   "Email": "ewawoloszyn7@gmail.com;info@luxurysicilyvillas.it",
   "Town": "",
   "Postcode": "",
   "Address": "Antura \nAshram\nCanalotto\nFalco\nPineta",
   "Notes": "Ewa - check in and client care\newawoloszyn7@gmail.com\nenquiries to marina at   \nCharts on following link\n\nhttp://secure.myalb.it/HomeMyAlb/app_login/\n\nAccess:\n6\nUsername: Essentialitaly\nPassword: Essentialitaly17\n "
 },
 {
   "RecordID": 211,
   "FirstName": "Jabia Beach House",
   "LastName": "",
   "Phone": "39.347.80.21.347",
   "Email": "pltmanagement@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Zarzana Roberto\nPers. mobile +39.393.05.43.294\ninternational n°+39 0924.076318 \n"
 },
 {
   "RecordID": 212,
   "FirstName": "Casa Faro Favignana",
   "LastName": "",
   "Phone": "",
   "Email": "info@casafarofavignana.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Giacomo"
 },
 {
   "RecordID": 213,
   "FirstName": "Mangiabove",
   "LastName": "",
   "Phone": "",
   "Email": "info@mangiabove.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Iggy"
 },
 {
   "RecordID": 214,
   "FirstName": "HomeinSicily",
   "LastName": "",
   "Phone": "",
   "Email": "info@homeinsicily.com",
   "Town": "",
   "Postcode": "",
   "Address": "Monacelli\nNausica\nPenelope\nSophia ",
   "Notes": "Clara - daughter of owner\nRoberta Minardi\nVilla Penelope\n\n+39 344 1480883  Vito Noto (+39 335 1338447) Property manager\n\n"
 },
 {
   "RecordID": 215,
   "FirstName": "The Orange Grove",
   "LastName": "",
   "Phone": "",
   "Email": "guendalina_auteri@yahoo.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "user name - daniela.oliva@essentialitaly.co.uk\npassword - daniela"
 },
 {
   "RecordID": 216,
   "FirstName": "Borgo Pantano",
   "LastName": "",
   "Phone": "",
   "Email": "info@borgopantano.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "manager Luigi Cavarra"
 },
 {
   "RecordID": 217,
   "FirstName": "Torre Sassa",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "La Vecchia Sassa\nVilla Torre Sassa ",
   "Notes": "La Vecchia Sassa, Iano, Montaione\nCinzia Ronchini\n\nhttps://book47.com/calendar/U5Z170FpTHNkaxh8DfYYWCZcgsqMPn/0\n\nhttps://book47.com/calendar/U5Z170FpTHNkaxh8DfYYWCZcgsqMPn/0\n\t\t\t\t\t\t\n"
 },
 {
   "RecordID": 218,
   "FirstName": "Villa Cristina",
   "LastName": "",
   "Phone": "",
   "Email": "info@villacristinatuscany.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Simone Butali"
 },
 {
   "RecordID": 219,
   "FirstName": "Siena House",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 220,
   "FirstName": "Porta Rossa ",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 221,
   "FirstName": "Villa Felice",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "http://www.dateblocker.com/AvailabilityCalendar/it?PropertyId=41725\n"
 },
 {
   "RecordID": 222,
   "FirstName": "Ca' di Gosto",
   "LastName": "",
   "Phone": "",
   "Email": "jennynichols@me.com",
   "Town": "",
   "Postcode": "",
   "Address": "Leoncino 14\nPerugia 06019",
   "Notes": "Jenny Nichols"
 },
 {
   "RecordID": 223,
   "FirstName": "Villa Pietra e Mattoni",
   "LastName": "",
   "Phone": "",
   "Email": "fgren@tuscanyitaly.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Franco Gren"
 },
 {
   "RecordID": 224,
   "FirstName": "Tenuta Sant' Illario",
   "LastName": "",
   "Phone": "",
   "Email": "info@tenutasantilario.it",
   "Town": "",
   "Postcode": "",
   "Address": "Tenuta Sant' Illario\nVilla Montagnola",
   "Notes": "Cristina and Valentina"
 },
 {
   "RecordID": 225,
   "FirstName": "Tenuta Moriano",
   "LastName": "",
   "Phone": "",
   "Email": "info@tenutamoriano.it",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Rossa\nCasolare San Lorenzo\nTenuta Moriano",
   "Notes": "www.moriano.it\n\nProbelem for TM sending us emails - use this one if problem reoccurs\npetra.stuprich@hotmail.it\n"
 },
 {
   "RecordID": 226,
   "FirstName": "Nina Trulli Resort",
   "LastName": "",
   "Phone": "",
   "Email": "info@ninatrulliresort.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 227,
   "FirstName": "Villa Silvana",
   "LastName": "",
   "Phone": "",
   "Email": "annatb@me.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Anna Tatton"
 },
 {
   "RecordID": 228,
   "FirstName": "Fly Home Sicily",
   "LastName": "",
   "Phone": "",
   "Email": "info@flyhomesicily.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Gisolfo\nVilla Athena ",
   "Notes": "info@flyhomesicily.com\nFrancesca\nLog in at the bottom of the website\nusername: essential\npassword: Essential1\n\n"
 },
 {
   "RecordID": 229,
   "FirstName": "Palazzo Melfi",
   "LastName": "",
   "Phone": "",
   "Email": "direzione@palazzomelfi.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 230,
   "FirstName": "Masseria Muntibianchi",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriamuntibianchi.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Alessandra"
 },
 {
   "RecordID": 231,
   "FirstName": "Cicò Hotel ",
   "LastName": "",
   "Phone": "",
   "Email": "info@cicohotel.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Salvatore Lanzilotti\nsalvatore 3286868601\n\nFront Office Manager\nPatrizia Cardo\n334 9990909 , \n388 3007590\n"
 },
 {
   "RecordID": 232,
   "FirstName": "Masseria Mongiò",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriamongio.com",
   "Town": "",
   "Postcode": "",
   "Address": "Baia dei Turchi, Otranto\n\nManager Salvatore\n\nConsulente Davide mandorino \n\n",
   "Notes": "Angelo Mongiò"
 },
 {
   "RecordID": 233,
   "FirstName": "Trullo Terra",
   "LastName": "",
   "Phone": "+39 339 357 01 76",
   "Email": "info@charmingtours.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Proper  name for requests Trullo Terra madre\nPina or Carmela are best contacts\n\nAlessandro Paiano"
 },
 {
   "RecordID": 234,
   "FirstName": "Trullo Bianco",
   "LastName": "",
   "Phone": "+39 339 357 01 76",
   "Email": "info@charmingtrulli.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Proper  name for requests Country Barsento\nPina or Carmela are best contacts\n\nAlessandro Paiano"
 },
 {
   "RecordID": 235,
   "FirstName": "Trulli Hotel",
   "LastName": "",
   "Phone": "",
   "Email": "info@charmingtrulli.com",
   "Town": "",
   "Postcode": "",
   "Address": "Charming Trulli Hotel, Piazza Sacramento, 8\n70011 Alberobello ( BA )",
   "Notes": "\nTel. +39 080 432 38 29  +39 339 357 01 76\n\nBookings to info@charmingtrulli.com"
 },
 {
   "RecordID": 236,
   "FirstName": "Masseria Trapaná",
   "LastName": "",
   "Phone": "",
   "Email": "info@trapana.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Rafaella"
 },
 {
   "RecordID": 237,
   "FirstName": "Trullo Pulcino",
   "LastName": "",
   "Phone": "",
   "Email": "jacobkrichefski@icloud.com",
   "Town": "",
   "Postcode": "",
   "Address": "Jacob Krichefski\nContrada Paradiso\n72017 Ostuni\nItalia\n",
   "Notes": "Housekeeper maria grazia 347 4727374 (no english)\n"
 },
 {
   "RecordID": 238,
   "FirstName": "Vinilia Wine Resort",
   "LastName": "",
   "Phone": "",
   "Email": "booking@viniliaresort.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Booking - Sigrid Siena\nbooking@viniliaresort.com\ninfo@viniliaresort.com"
 },
 {
   "RecordID": 239,
   "FirstName": "Villa Il Gallo",
   "LastName": "",
   "Phone": "",
   "Email": "info@casaledelgallo.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "luca (son) Patrizia (owner)"
 },
 {
   "RecordID": 240,
   "FirstName": "Villa Chio",
   "LastName": "",
   "Phone": "",
   "Email": "info@famigliabuccelletti.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 241,
   "FirstName": "Villa del Chianti",
   "LastName": "",
   "Phone": "",
   "Email": "rosedelchianti@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Calendar https://www.tripadvisor.co.uk/VacationRentalReview-g676810-d8759169-Villa_RoseDelChianti_amazing_country_cooking-Figline_e_Incisa_Valdarno_Tuscany.html\nELisabetta Morganti"
 },
 {
   "RecordID": 242,
   "FirstName": "Villa Guidi",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Franco Gren - Villa Posarelli\nPhone: 0039 3383746803\n\n\nhttp://www.posarellivillas.com/generic_search.html?search_action=search&search_pname=Villa+Casalguidi&search_uname=Villa+Casalguidi&search_page=1&search_sort_value=&search_sort_type=&search_agency_name=&search_country_id=&search_state_id=&search_area=&search_city_id=&search_destination=Villa+Casalguidi&search_start_date=&search_start_date_text=&search_end_date=&search_end_date_text=&search_capacity=\n"
 },
 {
   "RecordID": 243,
   "FirstName": "Villa dei Carrubi",
   "LastName": "",
   "Phone": "",
   "Email": "dr.mauriziodegiuli@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Prof Maurizio Degiuli"
 },
 {
   "RecordID": 244,
   "FirstName": "Hotel La Coluccia",
   "LastName": "",
   "Phone": "344 0860819 ",
   "Email": "booking@hotellacoluccia.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Manager Giani Miani 344 0860819\ndirezione@hotellacoluccia.com\nRosa reservations\nbooking@hotellacoluccia.com\nPatrizia Mastrucci Marketing\nmarketing@hotellacoluccia.com"
 },
 {
   "RecordID": 245,
   "FirstName": "Casa Fabio",
   "LastName": "",
   "Phone": "",
   "Email": "fabioghislotti@virgilio.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Fabio Ghislotti"
 },
 {
   "RecordID": 246,
   "FirstName": "Masseria Lavandula",
   "LastName": "",
   "Phone": "",
   "Email": "neil.parker1@yahoo.co.uk;manna.pondrelli@fremantlemedia.com",
   "Town": "",
   "Postcode": "",
   "Address": "21 Latimer Road, Cropston, Leicestershire LE7 7GP\nNeil Parker\nCheck availability with CV travel _Paola, Philip Leyton? Called Eterea on CV\nproduct.support@cvvillas.com\n\nHouse manager\nvalrice@hotmail.co.uk\n39 331 2576930\n \n\n\n\n ",
   "Notes": "21 Latimer Road, Cropston, Leicestershire LE7 7GP\nNeil Parker\nCheck availability with CV travel _Paola, Philip Leyton? Called Eterea on CV\nproduct.support@cvvillas.com\n\nHouse manager\nvalrice@hotmail.co.uk\n39 331 2576930\n \n\n\n\n "
 },
 {
   "RecordID": 247,
   "FirstName": "Villa Azzurra ",
   "LastName": "",
   "Phone": "",
   "Email": "blanchardallegra@gmail.com;arrivals@perfectpuglia.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Allegra Blanchard\n\nhttp://www.babyfriendlyboltholes.co.uk/child-friendly-accommodation/villa_azzurra-83262/#panel-overview\n\nhttp://www.furtherafield.com/villa-azzurra-puglia-italy?v=true\n\nblanchardallegra@gmail.com   meet and greet arrivals@perfectpuglia.com - Hayley\n"
 },
 {
   "RecordID": 248,
   "FirstName": "Trullo Casa Allegro",
   "LastName": "",
   "Phone": "",
   "Email": "trullo.allegro@gmail.com;paolacenturini@gmail.",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Gianmario allegro\nPaola Allegro "
 },
 {
   "RecordID": 249,
   "FirstName": "Masseria Morosetta ",
   "LastName": "",
   "Phone": "",
   "Email": "info@masseriamoroseta.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 250,
   "FirstName": "Trullo Bellissimo",
   "LastName": "",
   "Phone": "",
   "Email": "keithlbrown@hotmail.com;andrea.widdowson@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Availability = http://www.trullobellissimo.com/availability/\nKeith Brown"
 },
 {
   "RecordID": 251,
   "FirstName": "Il Falchetto",
   "LastName": "",
   "Phone": "(+39) 333 8034879",
   "Email": "info@santamariadegliancillotti.com",
   "Town": "",
   "Postcode": "",
   "Address": "Alessio Villa\nLocalità Sterpeto, 42 - Assisi (PG)",
   "Notes": ""
 },
 {
   "RecordID": 252,
   "FirstName": "Casa Fontefaggio",
   "LastName": "",
   "Phone": "+32.475791117",
   "Email": "eric.bauchau@gmail.com;ambrogi.simona@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "Fontefaggio - \nStrada Fratticiola Selvatica - Piccione\nFratticiola Selvatica\nPerugia\n",
   "Notes": "ERIC BAUCHAU\nGROTE BAAN 26\nB - 1620 - DROGENBOS\nBELGIUM\n\neric.bauchau@gmail.com - Simona - Caretaker - ambrogi.simona@tiscali.it\n\nMarco = 075 9229750\nSimona: 00393480130328\n\n"
 },
 {
   "RecordID": 253,
   "FirstName": "Monique",
   "LastName": "Titterton",
   "Phone": "00393348905081and 07955872957",
   "Email": "monique.ttrtn@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "0039075920363 Italian mobile 00393348905081\nUK mobile 07955872957"
 },
 {
   "RecordID": 254,
   "FirstName": "Franca and Umberto ",
   "LastName": "Costarelli",
   "Phone": "",
   "Email": "teocost@hotmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Franca ",
   "Notes": ""
 },
 {
   "RecordID": 255,
   "FirstName": "Neri ",
   "LastName": "Gazulli",
   "Phone": "00393298316890 Neri (Mobile)",
   "Email": "sanvito@san-vito.com",
   "Town": "",
   "Postcode": "",
   "Address": "Tenuta San Vito \nVia San Vito, 59 - 50056 Montelupo Fiorentino, Firenze, Italy\n",
   "Notes": "00390571 51411 Sara (Reception) or 00393298316890 Neri (Mobile)\n+393 979 6984. Elena\n\nTenuta San Vito\nPodere Frantoio"
 },
 {
   "RecordID": 256,
   "FirstName": "Podere San Luigi",
   "LastName": "",
   "Phone": "",
   "Email": "info@poderesanluigi.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Mario, Annalinda and Valentina www.casamanager.net\nuser - helen.forbes@essentialitaly.co.uk\nPassword - helen2012"
 },
 {
   "RecordID": 257,
   "FirstName": "Ivana ",
   "LastName": "",
   "Phone": "",
   "Email": "maurolii@liberto.it",
   "Town": "",
   "Postcode": "",
   "Address": "I Mandorli",
   "Notes": ""
 },
 {
   "RecordID": 258,
   "FirstName": "marina",
   "LastName": "bigazzi",
   "Phone": "",
   "Email": "info@torrinoestate.it",
   "Town": "",
   "Postcode": "",
   "Address": "Il Torrino\nVilla Lionella ",
   "Notes": "info@torrinomontaione.com"
 },
 {
   "RecordID": 259,
   "FirstName": "Poggio al Sole",
   "LastName": "",
   "Phone": "",
   "Email": "info@poggiosole.it",
   "Town": "",
   "Postcode": "",
   "Address": "C.S. 122 Valecchie Montanare\n52040 Cortona (AR)\n",
   "Notes": "Temp email address - faggio.rosso@libero.it\n"
 },
 {
   "RecordID": 260,
   "FirstName": "Le Querce",
   "LastName": "",
   "Phone": "",
   "Email": "giacintacatalano@vanriel.com",
   "Town": "",
   "Postcode": "",
   "Address": "Le Querce and Villa Leopoldina ",
   "Notes": "Email:  giacintacatalano@vanriel.com\n\nUK mobile:  07768 277009\nUK home:    0207 835 2870/1\n\nItalian mobile:  +39 333 235 4031\n\nHendrik van Riel:   07768 451555\n\nCiacinta - home - Flat 13, 29 Bramham Gardens, SW5 OHE\n\nNew PA until November Jo - jo@wimbledonpa.co.uk\n\njanmay@vanriel.com  - PA to Van Riels\nvalentina@vanriel.com  - Italian PA\n"
 },
 {
   "RecordID": 261,
   "FirstName": "Raffaello ",
   "LastName": "Pelucchini",
   "Phone": "",
   "Email": "raffaellop@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Caterina\nCasa Manuela\nVilla Il Sorbello",
   "Notes": "http://www.dateblocker.com/Index.aspx?Pageid=1548&l=1\n\nUsername; SilviaG\n\nPsw; costarica12\n\n\n\n"
 },
 {
   "RecordID": 262,
   "FirstName": "Edoardo",
   "LastName": "Giacone",
   "Phone": "",
   "Email": "edoardo@villaarmena.com.",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Armena ",
   "Notes": ""
 },
 {
   "RecordID": 263,
   "FirstName": "Villa Murella ",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 264,
   "FirstName": "The Royal Victoria ",
   "LastName": "",
   "Phone": "",
   "Email": "post@royalvictoria.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 265,
   "FirstName": "Villa Cretole",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 266,
   "FirstName": "le Terrazze",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "Antonella\n52041 Albergo (AR)\nVia Vierucci - Albergo 47\nGiada - +39 3334654422",
   "Notes": ""
 },
 {
   "RecordID": 267,
   "FirstName": "Pratello Country resort",
   "LastName": "",
   "Phone": "",
   "Email": "tenuta@pratello.it",
   "Town": "",
   "Postcode": "",
   "Address": "via Libbiano, 70\n56037 Peccioli (Pisa)\nAtt: Claudia",
   "Notes": ""
 },
 {
   "RecordID": 268,
   "FirstName": "Andrew ",
   "LastName": "Spitaleri",
   "Phone": "mobile +001 5162443084",
   "Email": "aspitaleri@mac.com;tennant@tiscali.it",
   "Town": "",
   "Postcode": "",
   "Address": "Ripiano",
   "Notes": "Andrew Spitaleri\n53 Market Lane\nClinton Corners, NY 12514\nContact Charlotte Tennant in Tuscany\n0039 340 2801507\nCharlotte - casacompletainfo@gmail.com\n\nCharlotte Mobile\n+39 3402801507\nCharlotte Home\n+39 0583 800097\nLaura Mobile\n+39 3407030901\nLaura Home\n+39 0583 800003\nCharlotte's parents\n020 8647 9723 \nNew owners - aspitaleri@mac.com - andrew Spitaleri\n\n\n"
 },
 {
   "RecordID": 269,
   "FirstName": "Jenni",
   "LastName": "Bird",
   "Phone": "",
   "Email": "jenni.bird@villasaletta.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Il Casolare",
   "Notes": ""
 },
 {
   "RecordID": 270,
   "FirstName": "Karin and Antonio",
   "LastName": "",
   "Phone": "",
   "Email": "sanmartino@montepulciano.com",
   "Town": "",
   "Postcode": "",
   "Address": "Fattoria San Martino\nVia Martiena, 3 - 53045 - MONTEPULCIANO\n\n",
   "Notes": "Marketting & PR activities = kraemer@triiimpuls.com  - Britta"
 },
 {
   "RecordID": 271,
   "FirstName": "Castello di Fonterutoli",
   "LastName": "",
   "Phone": "",
   "Email": "hospitality@mazzei.it",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 272,
   "FirstName": "Rosado",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Col di Forche",
   "Notes": "Villa Col di Forche\nCalendar\nhttps://www.to-tuscany.com/coldiforche/#price"
 },
 {
   "RecordID": 273,
   "FirstName": "Mariella & Enzo Bianchi ",
   "LastName": "",
   "Phone": "",
   "Email": "ebianchi39@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Santa Lucia\nSanta Lucia 10\nMonteriggioni 53035\nSiena\n",
   "Notes": "Santa Lucia\ncheck availability at ituscan.com - Casa Bianca\n\nenzo.bianchi@bianchielettronica.com ebianchi39@gmail.com - use this one"
 },
 {
   "RecordID": 274,
   "FirstName": "Bridget",
   "LastName": "Strange",
   "Phone": "",
   "Email": "bridget.strange@nielsen.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": "Anna Maria is caretaker - keys will be left in door for clients arriving\nhttps://www.holidaylettings.co.uk/rentals/coreglia-antelminelli/6925841 "
 },
 {
   "RecordID": 275,
   "FirstName": "Laura ",
   "LastName": "Faberi",
   "Phone": "",
   "Email": "laura.faberi@enel.com;florencecentreflats@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Ambrogio",
   "Notes": "Casa Ambrogio"
 },
 {
   "RecordID": 276,
   "FirstName": "Giulia",
   "LastName": "",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "Casa San Gimignano\t\t\t\t\t\t\t",
   "Notes": "Casa San Gimignano\t"
 },
 {
   "RecordID": 277,
   "FirstName": "Julia ",
   "LastName": "Hruska",
   "Phone": "mobil CH +41 78 622 00 85",
   "Email": "juliahruska@yahoo.de",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Casale Marittimo",
   "Notes": "Villa Casale Marittimo"
 },
 {
   "RecordID": 278,
   "FirstName": "Franca ",
   "LastName": "",
   "Phone": "",
   "Email": "info@lacortedelre.com",
   "Town": "",
   "Postcode": "",
   "Address": "La Corte del Re ",
   "Notes": ""
 },
 {
   "RecordID": 279,
   "FirstName": "Mario and Susie ",
   "LastName": "Pamplini",
   "Phone": " 0039 3453539322",
   "Email": "mpampanini@hotmail.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Geremia",
   "Notes": "00393453539322  o1284830035 00390587684186 - 0039 0587 684186 ( land line )\n                                           0039 3453539322  ( mobile )\n"
 },
 {
   "RecordID": 280,
   "FirstName": "Mario",
   "LastName": "",
   "Phone": "",
   "Email": "elenabaracchi@libero.it",
   "Town": "",
   "Postcode": "",
   "Address": "Borgo Elena \nlocalità Cegliolo 468 \n52044 Cortona Arezzo",
   "Notes": ""
 },
 {
   "RecordID": 281,
   "FirstName": "Antonella",
   "LastName": "",
   "Phone": "",
   "Email": "benedet.laura@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Nova ",
   "Notes": "Casa Nova \nLaura (agent) Antonella - Owner"
 },
 {
   "RecordID": 282,
   "FirstName": "Monica and Stefania",
   "LastName": "",
   "Phone": "",
   "Email": "info@casatoscavacanze.com",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Tosca ",
   "Notes": "Casa Tosca"
 },
 {
   "RecordID": 283,
   "FirstName": "Catia",
   "LastName": "",
   "Phone": "",
   "Email": "morenobotti@yahoo.it",
   "Town": "",
   "Postcode": "",
   "Address": "La Voce del Silenzio",
   "Notes": ""
 },
 {
   "RecordID": 284,
   "FirstName": "Linda and Paul",
   "LastName": "Allen",
   "Phone": "",
   "Email": "lallen@westlandgreen.demon.co.uk",
   "Town": "",
   "Postcode": "",
   "Address": "Villa Anna \nVia della Pineta 5\nCiterna\nUmbria\n06010\nPG",
   "Notes": "Villa Anna"
 },
 {
   "RecordID": 285,
   "FirstName": "Manuela",
   "LastName": "Guarguaglini",
   "Phone": "",
   "Email": "info@lasassolina.com",
   "Town": "",
   "Postcode": "",
   "Address": "Villa La Sassolina",
   "Notes": ""
 },
 {
   "RecordID": 286,
   "FirstName": "Alessandro & Laura",
   "LastName": "",
   "Phone": "",
   "Email": "info@agriturismoisorbi.it",
   "Town": "",
   "Postcode": "",
   "Address": "I Sorbi",
   "Notes": "I Sorbi"
 },
 {
   "RecordID": 287,
   "FirstName": "Jacopo",
   "LastName": "",
   "Phone": "",
   "Email": "jmenchi@gmail.com",
   "Town": "",
   "Postcode": "",
   "Address": "I Limoni\nVilla Cipresetto\nVilla San Iacopo",
   "Notes": "Same owner as for I Limoni and Villa San Iacopo\nhttp://www.posarellivillas.it/_1008_1_unit.phtm\nhttp://www.posarellivillas.com/italy/tuscany/foiano-della-chiana/15663/availability \n\n\nhttp://www.posarellivillas.com/italy/tuscany/valiano/1008 "
 },
 {
   "RecordID": 288,
   "FirstName": "Villa Le Barone",
   "LastName": "",
   "Phone": "",
   "Email": "info@villalebarone.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 289,
   "FirstName": "Palazzo Niccolini",
   "LastName": "",
   "Phone": "",
   "Email": "info@niccolinidomepalace.com",
   "Town": "",
   "Postcode": "",
   "Address": "",
   "Notes": ""
 },
 {
   "RecordID": 290,
   "FirstName": "Silvia (sofia)",
   "LastName": "",
   "Phone": "",
   "Email": "silvia.signorini@reteivo.it",
   "Town": "",
   "Postcode": "",
   "Address": "Casa Sofia",
   "Notes": ""
 },
 {
   "RecordID": 291,
   "FirstName": "Lorenzo",
   "LastName": "",
   "Phone": "",
   "Email": "lorenzo@cantinelarco.it",
   "Town": "",
   "Postcode": "",
   "Address": "Villa L'Arco",
   "Notes": "Villa L'Arco\n\ncantinelarco@gmail.com\nGiulia Mitola"
 },
 {
   "RecordID": 292,
   "FirstName": "Rino",
   "LastName": "Causapruno",
   "Phone": "",
   "Email": "",
   "Town": "",
   "Postcode": "",
   "Address": "Casa sul Mare \nPunta delle Formiche- Portopalo",
   "Notes": ""
 },
 {
   "RecordID": 293,
   "FirstName": "Castello di Granarola",
   "LastName": "",
   "Phone": "",
   "Email": "info@castellodigranarola.it",
   "Town": "",
   "Postcode": "",
   "Address": " Via Castello, 1 Granarola, Gradara (PU) Marche Italia",
   "Notes": ""
 },
 {
   "RecordID": 294,
   "FirstName": "Tenuta Le Tre Virtù",
   "LastName": "",
   "Phone": "",
   "Email": "info@tenutaletrevirtu.it",
   "Town": "",
   "Postcode": "",
   "Address": "Località Lucigliano, Via di Lucigliano 13\n 50037 Scarperia e San Piero - FLORENCE - TUSCANY - ITALY\nValentina e Christian",
   "Notes": "i"
 }
]
}